workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: Rap

    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifygame"
        XCODE_SCHEME: "App"
        TEAM_ID: "ERUH5NNQUB"
        PROFILE_NAME: "AppStore_com.metestudios.flowifygame"

    scripts:
      - name: Environment check
        script: |
          echo "Checking environment variables..."
          echo "KEY_ID length: ${#APP_STORE_CONNECT_KEY_ID}"
          echo "ISSUER_ID length: ${#APP_STORE_CONNECT_ISSUER_ID}"
          echo "KEY_CONTENT length: ${#APP_STORE_CONNECT_KEY_CONTENT}"
          echo "PRIVATE_KEY length: ${#CERTIFICATE_PRIVATE_KEY}"
          if [ ${#APP_STORE_CONNECT_KEY_ID} -eq 0 ]; then echo "WARNING: APP_STORE_CONNECT_KEY_ID IS EMPTY"; fi
          if [ ${#CERTIFICATE_PRIVATE_KEY} -eq 0 ]; then echo "WARNING: CERTIFICATE_PRIVATE_KEY IS EMPTY. Build may fail if no default cert exists."; fi

      - name: Install dependencies
        script: npm install

      - name: Build web assets
        script: npm run build

      - name: Capacitor Sync
        script: |
          if [ ! -f "ios/App/Podfile" ]; then
            echo "iOS project incomplete (missing Podfile). Reconstructing..."
            mkdir -p temp_ios_meta
            [ -d "ios/App/fastlane" ] && cp -r ios/App/fastlane temp_ios_meta/
            [ -f "ios/App/Gemfile" ] && cp ios/App/Gemfile temp_ios_meta/
            rm -rf ios
            npx cap add ios
            [ -d "temp_ios_meta/fastlane" ] && cp -r temp_ios_meta/fastlane ios/App/
            [ -f "temp_ios_meta/Gemfile" ] && cp temp_ios_meta/Gemfile ios/App/
          fi
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Fetch signing files
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates

      - name: Create exportOptions.plist
        script: |
          cat > /Users/builder/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROFILE_NAME</string>
              </dict>
          </dict>
          </plist>
          EOF
          cat /Users/builder/exportOptions.plist

      - name: Archive app
        script: |
          xcodebuild archive \
            -workspace ios/App/App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/ios/App.xcarchive \
            -configuration Release \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME"

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/App.xcarchive \
            -exportOptionsPlist /Users/builder/exportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
