workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowify"
        XCODE_SCHEME: "App"
        TEAM_ID: "ERUH5NNQUB"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "WJ3MJX52WS"
        APP_STORE_CONNECT_ISSUER_ID: "87981dc2-2287-419d-8eef-4560424acbdd"
    scripts:
      - name: Install dependencies
        script: npm install
      
      - name: Build web assets
        script: npm run build
      
      - name: Capacitor Sync & Assets
        script: |
          npm run assets:generate
          npx cap add ios || true
          npx cap sync ios
      
      - name: Install CocoaPods
        script: cd ios/App && pod install
      
      - name: Set up code signing
        script: |
          keychain initialize
          
          # Save API key to file
          echo -n "$APP_STORE_CONNECT_PRIVATE_KEY" > /tmp/AuthKey.p8
          
          # Fetch signing files using API key
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key @file:/tmp/AuthKey.p8
          
          keychain add-certificates
          xcode-project use-profiles --project ios/App/App.xcodeproj
      
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        api_key: /tmp/AuthKey.p8
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
