# Check out https://docs.codemagic.io/yaml/yaml-getting-started/ for more information
# about the codemagic.yaml file.

workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: flowify_mobile
    environment:
      groups:
        - google_play # Defined in Codemagic UI for publishing if needed
      vars:
        PACKAGE_NAME: "com.metestudios.flowify"
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  ios-app-store-workflow:
    name: iOS App Store Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: flowify_mobile
    environment:
      groups:
        - apple_auth
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.metestudios.flowify
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --bundle-sks-path ios/Runner/Assets.xcassets \
            --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
