# Check out https://docs.codemagic.io/yaml/yaml-getting-started/ for more information
# about the codemagic.yaml file.

workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: flowify_mobile
    environment:
      groups:
        - google_play # Defined in Codemagic UI for publishing if needed
      vars:
        PACKAGE_NAME: "com.metestudios.flowify"
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: flowify_mobile
    environment:
      groups:
        - apple_auth # Defined in Codemagic UI for App Store Connect
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
