workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Zeal
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowify"
        XCODE_SCHEME: "App"
        TEAM_ID: "ERUH5NNQUB"
    scripts:
      - name: Install dependencies
        script: npm install
      
      - name: Build web assets
        script: npm run build
      
      - name: Capacitor Sync & Assets
        script: |
          npm run assets:generate
          npx cap add ios || true
          npx cap sync ios
      
      - name: Install CocoaPods
        script: cd ios/App && pod install
      
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          
          # Get the provisioning profile name
          PROFILE_PATH=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision | head -1)
          PROFILE_NAME=$(grep -aA1 "Name" "$PROFILE_PATH" | grep string | sed -E 's/.*<string>(.*)<\/string>.*/\1/' | head -1)
          PROFILE_UUID=$(grep -aA1 "UUID" "$PROFILE_PATH" | grep string | sed -E 's/.*<string>(.*)<\/string>.*/\1/' | head -1)
          echo "Profile Name: $PROFILE_NAME"
          echo "Profile UUID: $PROFILE_UUID"
          
          # Apply profiles to project
          xcode-project use-profiles --project ios/App/App.xcodeproj
      
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
