workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: Rap

    environment:
      groups:
        - app_store_credentials # Create this group in Codemagic UI and add your secrets there
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifygame"
        XCODE_SCHEME: "App"
        TEAM_ID: "ERUH5NNQUB"
        PROFILE_NAME: "AppStore_com.metestudios.flowifygame"

    scripts:
      - name: Environment check
        script: |
          echo "Checking environment variables..."
          [ -z "$APP_STORE_CONNECT_KEY_ID" ] && echo "ERROR: APP_STORE_CONNECT_KEY_ID is missing" || echo "APP_STORE_CONNECT_KEY_ID is set"
          [ -z "$APP_STORE_CONNECT_ISSUER_ID" ] && echo "ERROR: APP_STORE_CONNECT_ISSUER_ID is missing" || echo "APP_STORE_CONNECT_ISSUER_ID is set"
          [ -z "$APP_STORE_CONNECT_KEY_CONTENT" ] && echo "ERROR: APP_STORE_CONNECT_KEY_CONTENT is missing" || echo "APP_STORE_CONNECT_KEY_CONTENT is set"
      - name: Install dependencies
        script: npm install

      - name: Build web assets
        script: npm run build

      - name: Capacitor Sync
        script: |
          if [ ! -f "ios/App/Podfile" ]; then
            echo "iOS project incomplete (missing Podfile). Reconstructing..."
            mkdir -p temp_ios_meta
            [ -d "ios/App/fastlane" ] && cp -r ios/App/fastlane temp_ios_meta/
            [ -f "ios/App/Gemfile" ] && cp ios/App/Gemfile temp_ios_meta/
            rm -rf ios
            npx cap add ios
            [ -d "temp_ios_meta/fastlane" ] && cp -r temp_ios_meta/fastlane ios/App/
            [ -f "temp_ios_meta/Gemfile" ] && cp temp_ios_meta/Gemfile ios/App/
          fi
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Install Ruby dependencies
        script: |
          cd ios/App
          bundle install

      - name: Fastlane Build & Deploy
        script: |
          cd ios/App
          bundle exec fastlane beta

    artifacts:
      - ios/App/build/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
